[package]
name = "dolphin_auto_updater"
version = "0.1.0"
edition = "2021"

[dependencies]
fatfs = { git = "https://github.com/rafalh/rust-fatfs", version = "0.4", default-features = false, features = ["lfn", "std"] }
fscommon = "0.1.1"
xz2 = "0.1.6"
git2 = "0.13.2"
colored = "2.0.0"